services:
  app:
    build: .
    container_name: node-order-portal-app
    env_file:
      - .env
    ports:
      - "3002:3002"
      - "9229:9229"
    depends_on:
      - mongo
    command: sh -c "node --inspect=0.0.0.0:9229 src/index.js"

  mongo:
    image: mongo:7
    container_name: node-order-portal-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
